#!/bin/bash

# ===========================================
# Portfolio VPS Setup Script
# ===========================================
# Run this ONCE on your VPS server
# Usage: bash setup-vps.sh your@email.com
# ===========================================

set -e

# Check if email provided
if [ -z "$1" ]; then
    echo "❌ Error: Email required for SSL certificate"
    echo "Usage: bash setup-vps.sh your@email.com"
    exit 1
fi

EMAIL=$1
DOMAIN="chinardeshpande.tech"

echo "🚀 Setting up Portfolio on VPS..."
echo "📧 Email: $EMAIL"
echo "🌐 Domain: $DOMAIN"
echo ""

# Create directories
echo "📁 Creating directories..."
mkdir -p /var/www/portfolio/certbot/{conf,www}
mkdir -p /var/www/portfolio/docker/nginx
mkdir -p /var/www/portfolio/logs/nginx

cd /var/www/portfolio

# Check Docker
echo "🐳 Checking Docker..."
if ! command -v docker &> /dev/null; then
    echo "❌ Docker not found. Installing..."
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    rm get-docker.sh
fi

if ! command -v docker-compose &> /dev/null; then
    echo "❌ Docker Compose not found. Installing..."
    apt update
    apt install -y docker-compose
fi

echo "✅ Docker ready: $(docker --version)"
echo "✅ Docker Compose ready: $(docker-compose --version)"

# Create temporary nginx for SSL challenge
echo "🔧 Creating temporary nginx for SSL setup..."
cat > docker/nginx/temp.conf << 'NGINXCONF'
server {
    listen 80;
    server_name chinardeshpande.tech www.chinardeshpande.tech;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 200 'Portfolio VPS ready for SSL setup';
        add_header Content-Type text/plain;
    }
}
NGINXCONF

# Start temporary nginx
echo "🌐 Starting temporary nginx..."
docker stop nginx-temp 2>/dev/null || true
docker rm nginx-temp 2>/dev/null || true

docker run -d --name nginx-temp \
  -p 80:80 \
  -v $(pwd)/docker/nginx/temp.conf:/etc/nginx/conf.d/default.conf:ro \
  -v $(pwd)/certbot/www:/var/www/certbot:ro \
  nginx:alpine

sleep 3

# Get SSL certificate
echo "🔒 Obtaining SSL certificate from Let's Encrypt..."
echo "   This may take a minute..."

docker run -it --rm \
  -v $(pwd)/certbot/conf:/etc/letsencrypt \
  -v $(pwd)/certbot/www:/var/www/certbot \
  certbot/certbot certonly \
  --webroot \
  --webroot-path=/var/www/certbot \
  --email $EMAIL \
  --agree-tos \
  --no-eff-email \
  -d $DOMAIN \
  -d www.$DOMAIN

if [ $? -eq 0 ]; then
    echo "✅ SSL certificate obtained successfully!"
else
    echo "❌ SSL certificate failed. Check DNS settings:"
    echo "   $DOMAIN must point to this server's IP"
    exit 1
fi

# Stop temporary nginx
echo "🧹 Cleaning up temporary nginx..."
docker stop nginx-temp
docker rm nginx-temp

# Set up firewall
echo "🔥 Configuring firewall..."
if command -v ufw &> /dev/null; then
    ufw allow 22/tcp   # SSH
    ufw allow 80/tcp   # HTTP
    ufw allow 443/tcp  # HTTPS
    ufw --force enable
    echo "✅ Firewall configured"
else
    echo "⚠️  UFW not found, skipping firewall setup"
fi

# Create a placeholder .env file
echo "📝 Creating placeholder .env file..."
cat > .env << 'ENVFILE'
# This will be replaced by GitHub Actions on deployment
# DO NOT edit this file manually
NEXTAUTH_URL=https://chinardeshpande.tech
NEXTAUTH_SECRET=placeholder
ADMIN_EMAIL=placeholder
ADMIN_PASSWORD=placeholder
GOOGLE_CLIENT_ID=placeholder
GOOGLE_CLIENT_SECRET=placeholder
GOOGLE_REFRESH_TOKEN=placeholder
GA4_PROPERTY_ID=placeholder
SEARCH_CONSOLE_SITE_URL=https://chinardeshpande.tech
ENVFILE

# Display summary
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  ✅ VPS Setup Complete!                                    ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 What was done:"
echo "  ✅ Directory structure created"
echo "  ✅ Docker & Docker Compose verified"
echo "  ✅ SSL certificate obtained for $DOMAIN"
echo "  ✅ Firewall configured (ports 22, 80, 443)"
echo "  ✅ Ready for GitHub Actions deployment"
echo ""
echo "📍 Portfolio directory: /var/www/portfolio"
echo "🔒 SSL certificate: /var/www/portfolio/certbot/conf/live/$DOMAIN/"
echo ""
echo "🎯 Next steps:"
echo "  1. Add GitHub secrets (see below)"
echo "  2. Push code: git push origin main"
echo "  3. Watch deployment in GitHub Actions"
echo "  4. Visit: https://$DOMAIN"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "📝 COPY THESE VALUES FOR GITHUB SECRETS"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "PRODUCTION_SERVER_IP=$(curl -s ifconfig.me)"
echo ""
echo "PRODUCTION_SSH_KEY="
echo "  Run on your LOCAL machine: cat ~/.ssh/id_rsa"
echo "  Copy the entire output including BEGIN/END lines"
echo ""
echo "Get other secrets from Netlify or your .env.local file"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "✨ VPS is ready for deployment!"
echo ""
